version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      # - export PATH="C:\Program Files\7-Zip:$PATH"
      # - 7z a -tzip -mx9 ../deployment_package.zip .
      - zip -r9 ../deployment_package.zip .
      - cd ..
      # - 7z u deployment_package.zip lambda_function.py
      - zip -g deployment_package.zip lambda_function.py
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deployment_package.zip s3://lambda-builds-zip12/
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name doordash-lambda --s3-bucket lambda-builds-zip12 --s3-key deployment_package.zip
      - echo "Deployment complete!"
